farmacia/apps/clientes/urls.py
from django.conf.urls import patterns, url
from .views import CreateCliente, ListaCliente, DetalleView, ActualizarView, EliminarView

urlpatterns = patterns('',		
	#clientes
	url(r'^lista_clientes/$', ListaCliente.as_view(), name = 'lista_clientes'),
	url(r'^detalle_cliente/(?P<pk>\d+)/$', DetalleView.as_view(), name ='detalle_cliente'),
	url(r'^actualizar_clientes/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_clientes"), 
	url(r'^eliminar_cliente/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_cliente"), 
	url(r'^create_clientes/$', CreateCliente.as_view(), name='create_clientes'),
  )

farmacia/apps/users/urls.py
from django.conf.urls import patterns, url
from .views import Home

urlpatterns = patterns('',
	url(r'^$', 'apps.users.views.userlogin', name="login"),
	url(r'^salir/$', 'apps.users.views.LogOut', name = 'logout'),
#principal
	url(r'^home', Home.as_view(), name='home'),
)

farmacia/farmacia/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'farmacia.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #productos
    url(r'^', include('apps.medicamentos.urls', namespace="medicamentos_app")),

    #agregar ventas.
    url(r'^ventas/', include('apps.ventas.urls', namespace="ventas_app")),

    #login-users
    url(r'^', include('apps.users.urls',  namespace='users_app')),

    #CLientes
    url(r'^', include('apps.clientes.urls',  namespace='clientes_app')),


 #Distribuidores
    url(r'^', include('apps.distribuidor.urls',  namespace='distribuidores_app')),

        #compras
    url(r'^', include('apps.compras.urls',  namespace='compras_app')),
       #compras
    url(r'^', include('apps.laboratorio.urls',  namespace='laboratorios_app')),

     url(r'^todolist/', include('apps.inline.urls',  namespace='todolist')),

       #factura
     url(r'^', include('apps.factura.urls',  namespace='factura_app')),

)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
        )

farmacia/apps/clientes/models.py
 # -*- coding: utf-8 -*- 
from django.db import models
from django.conf import settings

class Cliente(models.Model):
	dni = models.IntegerField(unique=True)	
	nombre = models.CharField(max_length=60)
	apellidos = models.CharField(max_length=100)
	direccion = models.CharField(max_length=100)
	telefono = models.IntegerField(verbose_name='Telefono')

	def __unicode__(self):
		return self.nombre

farmacia/apps/clientes/forms.py
#encoding:utf-8
from django import forms
from apps.clientes.models import Cliente

class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente

	dni = forms.CharField(widget=forms.NumberInput(attrs={
		'placeholder': 'DNI',
		'size': '8'}))
	nombre = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Nombre Cliente',
		'size': '40'}))	
	apellidos = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Apellidos',
		'size': '40'}))		
	direccion = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Direccion',
		'size': '40'}))	
	telefono = forms.CharField(widget=forms.NumberInput(attrs={
		'placeholder': 'Telefono',
		'size': '8'}))

	def clean_dni(self):
		diccionario_limpio = self.cleaned_data
		dni = diccionario_limpio.get('dni')
		if len(dni) < 8 or len(dni) > 8:
			raise forms.ValidationError("debe ser de 8 Digitos")
		return dni

	def clean_nombre(self):
		nombre = self.cleaned_data['nombre']
		if not nombre.isalpha():
			raise forms.ValidationError('No puede contener números')
		return nombre

farmacia/apps/clientes/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView, ListView, DetailView
from .models import Cliente
from .forms import ClienteForm
from braces.views import LoginRequiredMixin,GroupRequiredMixin

class ListaCliente(LoginRequiredMixin,GroupRequiredMixin, ListView):
	context_object_name = 'clientes'
	model = Cliente
	template_name = 'clientes/lista_cliente.html'
	group_required = ['trabajadores']


# Create your views here.
class DetalleView(LoginRequiredMixin, DetailView):
	model = Cliente
	template_name = 'clientes/detalle_clientes.html'


class ActualizarView(UpdateView):
	form_class = ClienteForm
	template_name = 'clientes/create_update_clientes.html'
	model = Cliente
	success_url='/lista_clientes'



class EliminarView(GroupRequiredMixin, DeleteView):
	model = Cliente
	success_url='/lista_clientes'
	template_name = 'clientes/eliminar_cliente.html'
	group_required = ['administrador']



class CreateCliente(LoginRequiredMixin, CreateView):
	form_class = ClienteForm
	template_name = 'clientes/create_update_clientes.html'
	model = Cliente
	success_url = '/lista_clientes'

farmacia/templates/clientes/base_cliente_lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css %}
{% block js %}
   
    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock js %}

farmacia/templates/clientes/base_clientes.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/static/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="/static/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/static/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/static/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker-bs3.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
{% endblock css %}

{% block js %}
    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="/static/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="/static/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/static/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/static/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/static/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="/static/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/static/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/static/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
{% endblock js %}

farmacia/templates/clientes/create_update_clientes.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Clientes
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li><a href="{% url 'clientes_app:lista_clientes' %}">Clientes</a></li>
            <li class="active">Nuevo Cliente</li>
          </ol>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post">
                            {% csrf_token %} 
                            <div class="row">                              
                                <div class="col-xs-12 col-sm-10">                               
                                    <div class="form-group has-success has-feedback  {% if form.dni.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.dni.label_tag }}</label>
                                        <div class="col-sm-6">               
                                            <input type="text" name="dni" class="form-control" value='{% if form.dni.value %}{{ form.dni.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.dni.errors.as_text}}' autofocus='true' id="disabledInput" type="text" >                                          
                                        </div>
                                    </div> 
                                     
                                    <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="nombre" class="form-control" value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div>  
                                    <div class="form-group has-success has-feedback  {% if form.apellidos.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.apellidos.label_tag }}</label>
                                         <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="apellidos" class="form-control" value='{% if form.apellidos.value %}{{ form.apellidos.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.apellidos.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div> 
                                   
  
                                    <div class="form-group has-success has-feedback  {% if form.direccion.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.direccion.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="text" id="disabledTextInput" name="direccion" class="form-control" value='{% if form.direccion.value %}{{ form.direccion.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.direccion.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                    </div>  
                                    <div class="form-group has-success has-feedback  {% if form.telefono.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.telefono.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                            <input type="number" id="disabledTextInput" name="telefono" class="form-control" value='{% if form.telefono.value %}{{ form.telefono.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.telefono.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                       </div>                                    
                                </div>                                                        
                            </div> <!--<div class="row"> -->                                        
                                <div class="panel-footer color-footer">
                                    <button type="submit" class="btn btn-primary">
                                                 Grabar
                                    </button>
                                </div>               
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/clientes/detalle_clientes.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
          
            <div class="box-header with-border">
          		<a href="{% url 'clientes_app:lista_clientes' %}" class="btn btn-success">
            		<span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>              
              		<div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->            
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
	                    <tbody> 
	                          <tr class="success"> 
	                          	  <td><strong>DNI:</strong></td>                           
	                              <td>{{ object.dni }}</td>
	                          </tr>
	                          <tr class="success">
	                          	  <td><strong>Nombre:</strong></td>
	                              <td>{{ object.nombre }} </td> 
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Apellidos:</strong></td>
	                              <td>{{ object.apellidos }}</td>                              
	                           </tr>
	                           	                           <tr class="success">
	                           	  <td><strong>Dirección:</strong></td>
	                              <td>{{ object.direccion }}</td>                              
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Teléfono:</strong> </td>
	                              <td>{{ object.telefono}}</td>                  
	                           </tr>                           
	                    </tbody>
	               	</table>                                 
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/clientes/eliminar_cliente.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al cliente "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'clientes_app:lista_clientes' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/clientes/lista_cliente.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}    
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Clientes
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Clientes</li>
            <li><a href="{% url 'clientes_app:create_clientes' %}">Nuevo Clientes</a></li>
            
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'clientes_app:create_clientes' %}" class="btn btn-success">
                      Nuevo Cliente
                    </a></h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>DNI</th>                       
                        <th>Nombre</th> 
                        <th>Apellidos</th>                              
                        <th>Teléfono</th>
                        <th>Acciones</th>                       
                      </tr>
                    </thead>
                    <tbody>
                    
                     {% for clientes in clientes %}          

                        <tr> 
                          <td>{{ forloop.counter}}</td>
                          <td>{{ clientes.dni }}</td>
                          <td>{{ clientes.nombre }} </td> 
                          <td>{{ clientes.apellidos }}</td>                              
                          <td>{{ clientes.telefono}}</td>
                          <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{% url 'clientes_app:detalle_cliente' clientes.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}

                                  <a href="{% url 'clientes_app:actualizar_clientes' clientes.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% for group in user.groups.all %}
                                     {% if group.name == 'administrador' %}
                                  <a href="{% url 'clientes_app:eliminar_cliente' clientes.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a> 
                                   {% endif %}
                                   {% endfor %}
                            </td>                      
                              
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}