farmacia/apps/laboratorio/urls.py
from django.conf.urls import patterns, url
from .views import CreateLaboratorio, ListaLaboratorio, DetalleView, ActualizarView, EliminarView

urlpatterns = patterns('',		
	#clientes
	url(r'^lista_laboratorios/$', ListaLaboratorio.as_view(), name = 'lista_laboratorios'),
	url(r'^detalle_laboratorios/(?P<pk>\d+)/$', DetalleView.as_view(), name ='detalle_laboratorios'),
	url(r'^actualizar_laboratorios/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_laboratorios"), 
	url(r'^eliminar_laboratorios/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_laboratorios"), 
	url(r'^create_laboratorios/$', CreateLaboratorio.as_view(), name='create_laboratorios'),
  )

farmacia/apps/users/urls.py
from django.conf.urls import patterns, url
from .views import Home

urlpatterns = patterns('',
	url(r'^$', 'apps.users.views.userlogin', name="login"),
	url(r'^salir/$', 'apps.users.views.LogOut', name = 'logout'),
#principal
	url(r'^home', Home.as_view(), name='home'),
)

farmacia/farmacia/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'farmacia.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #productos
    url(r'^', include('apps.medicamentos.urls', namespace="medicamentos_app")),

    #agregar ventas.
    url(r'^ventas/', include('apps.ventas.urls', namespace="ventas_app")),

    #login-users
    url(r'^', include('apps.users.urls',  namespace='users_app')),

    #CLientes
    url(r'^', include('apps.clientes.urls',  namespace='clientes_app')),


 #Distribuidores
    url(r'^', include('apps.distribuidor.urls',  namespace='distribuidores_app')),

        #compras
    url(r'^', include('apps.compras.urls',  namespace='compras_app')),
       #compras
    url(r'^', include('apps.laboratorio.urls',  namespace='laboratorios_app')),

     url(r'^todolist/', include('apps.inline.urls',  namespace='todolist')),

       #factura
     url(r'^', include('apps.factura.urls',  namespace='factura_app')),

)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
        )

farmacia/apps/laboratorio/models.py
from django.db import models

# Create your models here.
class Laboratorio(models.Model):
	codigo = models.CharField(max_length=10)
	nombre = models.CharField(max_length=40)
	sanitario = models.CharField(max_length=50)
	autorizacion = models.CharField(max_length=50)

	def __unicode__(self):
		return self.nombre
#agregar direccion

farmacia/apps/laboratorio/forms.py
#encoding:utf-8
from django import forms
from .models import Laboratorio

class ClienteForm(forms.ModelForm):
	class Meta:
		model = Laboratorio

farmacia/apps/laboratorio/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView, ListView, DetailView
from .models import Laboratorio
from .forms import ClienteForm
from braces.views import LoginRequiredMixin,GroupRequiredMixin

class ListaLaboratorio(LoginRequiredMixin,GroupRequiredMixin, ListView):
	context_object_name = 'laboratorios'
	model = Laboratorio
	template_name = 'laboratorios/lista_laboratorio.html'
	group_required = ['trabajadores']




# Create your views here.
class DetalleView(LoginRequiredMixin, DetailView):
	model = Laboratorio
	template_name = 'laboratorios/detalle_laboratorio.html'


class ActualizarView(UpdateView):
	form_class = ClienteForm
	template_name = 'laboratorios/crear_laboratorios.html'
	model = Laboratorio
	success_url='/lista_laboratorio'



class EliminarView(GroupRequiredMixin, DeleteView):
	model = Laboratorio
	success_url='/lista_laboratorio'
	template_name = 'laboratorios/eliminar_laboratorio.html'
	group_required = ['administrador']



class CreateLaboratorio(LoginRequiredMixin, CreateView):
	
	template_name = 'laboratorios/crear_laboratorios.html'
	model = Laboratorio
	success_url = '/lista_laboratorio'

farmacia/templates/laboratorios/base_laboratorios.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css %}
{% block js %}
   
    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock js %}

farmacia/templates/laboratorios/crear_laboratorios.html
{% extends "laboratorios/base_laboratorios.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Laboratorio
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li><a href="{% url 'laboratorios_app:lista_laboratorios' %}">Laboratorios</a></li>
            <li class="active">Nuevo Laboratorio</li>
          </ol>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
    <div class="row">
      <div class="col-lg-12">
        <form class="form-horizontal" method="post">
                {% csrf_token %}    
                <div class="panel panel-primary">
                   <div class="panel-heading">Laboratorio</div>
                    <div class="panel-body">
                        <div class="page-header">                            
                        <h4>
                            <a href="{% url 'laboratorios_app:lista_laboratorios' %}" class="btn btn-success">
                            <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                            </a>
                            
                        </h4>
                        </div><!-- page-header -->
                        <div class="row">                              
                            <div class="col-xs-12 col-sm-10">                               
                                <div class="form-group has-success has-feedback  {% if form.codigo.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.codigo.label_tag }}</label>
                                        <div class="col-sm-2">                                        
                                        <input type="number" id="disabledTextInput" name="codigo" class="form-control" value='{% if form.codigo.value %}{{ form.codigo.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.codigo.errors.as_text}}' autofocus='true' >                                         
                                        </div>
                                  </div> 
                                <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="nombre" class="form-control" value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div>  
                                <div class="form-group has-success has-feedback  {% if form.sanitario.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.sanitario.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="sanitario" class="form-control" value='{% if form.sanitario.value %}{{ form.sanitario.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.sanitario.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div> 
                                <div class="form-group has-success has-feedback  {% if form.autorizacion.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.autorizacion.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="autorizacion" class="form-control" value='{% if form.autorizacion.value %}{{ form.autorizacion.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.autorizacion.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div>                                   
                            </div>                                                        
                        </div> <!--<div class="row"> -->
                        
                        <div class="panel-footer color-footer">
                            <button type="submit" class="btn btn-primary">
                                 Grabar
                            </button>
                        </div>
 

                    </div>
                </div>
        </form>
      </div>
  </div><!--/.row-->
</div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/laboratorios/detalle_laboratorio.html
{% extends "clientes/base_clientes.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}  
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">     
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Laboratorios</li>
      </ol>
    </div><!--/.row-->
    
    <div class="row">
      <div class="col-lg-12">
        <div class="row"> 
			<div class="col-xs-12 col-sm-6">
			<!-- jumbotron-->
				<div class="jumbotron">	
					<a href="{% url 'laboratorios_app:lista_laboratorios' %}" class="btn btn-success">
					    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
					</a>
					<table class="table table-striped table table-hover ">
	                        <thead>
	                            <tr>
	                             <th><h2> Detalle clientes </h2></th>           
	                           </tr>
	                        </thead>
	                      <tbody> 
	                          <tr class="success"> 
	                          	  <td><strong>Código:</strong></td>                           
	                              <td>{{ object.codigo }}</td>
	                          </tr>
	                          <tr class="success">
	                          	  <td><strong>Nombre:</strong></td>
	                              <td>{{ object.nombre }} </td> 
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Sanitario:</strong></td>
	                              <td>{{ object.sanitario }}</td>                              
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Autorización:</strong></td>
	                              <td>{{ object.autorizacion }}</td>                              
	                           </tr>
	                                                  
	                       </tbody>
	                </table>
	            </div>	<!-- end jumbotron-->				
		</div>	
      </div>
  </div><!--/.row-->
{% endblock producto %}
{% endblock content %}

farmacia/templates/laboratorios/editar_laboratorios.html
{% extends "laboratorios/base_laboratorios.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}  
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">     
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Laboratorios</li>
      </ol>
    </div><!--/.row-->
    
    <div class="row">
      <div class="col-lg-12">
        <form class="form-horizontal" method="post">
                {% csrf_token %}    
                <div class="panel panel-primary">
                   <div class="panel-heading">Actualizar Laboratorios</div>
                    <div class="panel-body">
                        <div class="page-header">                            
                        <h4>
                            <a href="{% url 'laboratorios_app:lista_laboratorios' %}" class="btn btn-success">
                            <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                            </a>
                            
                        </h4>
                        </div><!-- page-header -->
                        <div class="row">                              
                            <div class="col-xs-12 col-sm-10">                               
                                <div class="form-group has-success has-feedback  {% if form.codigo.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.codigo.label_tag }}</label>
                                        <div class="col-sm-6">               
                                        <input type="text" name="codigo" class="form-control" value='{% if form.codigo.value %}{{ form.codigo.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.codigo.errors.as_text}}' autofocus='true' id="disabledInput" type="text" disabled >                                          
                                        </div>
                                  </div> 
                                <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="nombre" class="form-control" value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div>  
                                <div class="form-group has-success has-feedback  {% if form.sanitario.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.sanitario.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="sanitario" class="form-control" value='{% if form.sanitario.value %}{{ form.sanitario.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.sanitario.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div> 
                                <div class="form-group has-success has-feedback  {% if form.autorizacion.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-2" for="inputSuccess3">{{ form.autorizacion.label_tag }}</label>
                                        <div class="col-sm-6">                                        
                                        <input type="text" id="disabledTextInput" name="autorizacion" class="form-control" value='{% if form.autorizacion.value %}{{ form.autorizacion.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.autorizacion.errors.as_text}}' autofocus='true'>                                       
                                        </div>
                                  </div> 
                                                            
                            </div>                                                        
                        </div> <!--<div class="row"> -->
                        
                        <div class="panel-footer color-footer">
                            <button type="submit" class="btn btn-primary">
                                 Grabar
                            </button>
                        </div>
 

                    </div>
                </div>
 </form>
      </div>
  </div><!--/.row-->
{% endblock producto %}
{% endblock content %}

farmacia/templates/laboratorios/eliminar_laboratorio.html
{% extends "clientes/base_clientes.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}  
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">     
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Clientes</li>
      </ol>
    </div><!--/.row-->
    
    <div class="row">
      <div class="col-lg-12">
        <div class="row"> 
			<div class="col-xs-12 col-sm-6">
				<h1> Eliminar</h1>
			<form method="POST">
				{% csrf_token %}
				<p class="coloreliminar">¿Desea eliminar al Laboratorios "{{ object.nombre }}?</p>
			       <input type="submit" value="Sí" class="btn btn-danger"> 
			       <a href="{% url 'laboratorios_app:lista_laboratorios' %}" class="btn btn-default">No</a>
			 </form>
		</div>	
      </div>
  </div><!--/.row-->
{% endblock producto %}
{% endblock content %}

farmacia/templates/laboratorios/lista_laboratorio.html
{% extends "laboratorios/base_laboratorios.html"%}
{% block content %}
{% include "nav.html" %}
{% block producto %}    
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Laboratorios
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Laboratorios</li>
            <li><a href="{% url 'laboratorios_app:create_laboratorios' %}">Nuevo Laboratorio</a></li>
            
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'laboratorios_app:create_laboratorios' %}" class="btn btn-success">
                      Nuevo Laboratorio
                    </a></h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                   <thead>
                            <tr>
                             <th>N°</th>
                              <th>Código</th>                       
                              <th>Nombre</th> 
                              <th>Sanitario</th>                              
                              <th>Autorizacion</th> 
                              <th>Acciones</th>                      
                           </tr>
                        </thead>
                    <tbody>
                    
                     {% for l in laboratorios %}          

                          <tr> 
                              <td>{{ forloop.counter}}</td>
                              <td>{{ l.codigo }}</td>
                              <td>{{ l.nombre }} </td> 
                              <td>{{ l.sanitario }}</td>                              
                              <td>{{ l.autorizacion}}</td>                      
                              <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{% url 'laboratorios_app:detalle_laboratorios' l.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}

                                  <a href="{% url 'laboratorios_app:actualizar_laboratorios' l.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% for group in user.groups.all %}
                                      {% if group.name == 'administrador' %}
                                  <a href="{% url 'laboratorios_app:eliminar_laboratorios' l.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a> 
                                    {% endif %}
                                    {% endfor %}
                              </td>
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}