farmacia/apps/medicamentos/urls.py
from django.conf.urls import patterns, url
from .views import ListaMedicamentos, DetalleView,ActualizarView, CreateMedicamentos, EliminarView, CreatePresentacion

urlpatterns = patterns('',

	url(r'^medicamentos/$', ListaMedicamentos.as_view(), name = 'lista_medicamentos'),
	url(r'^medicamentos/detalle/(?P<pk>\d+)/$', DetalleView.as_view(), name ='detalle_medicamentos'),
	url(r'^medicamentos/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_medicamentos"),
	url(r'^medicamentos/agregar$', CreateMedicamentos.as_view(), name='create_medicamentos'),
	url(r'^medicamentos/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_medicamentos"), 
	#exportar a excel
	#url(r'^expatenciones/$', 'apps.medicamentos.views.CargaAtenciones_ant',name='xds'),
	url(r'^medicamentos/reporte/$', 'apps.medicamentos.views.generar_reporte_medicamentos',name='reporte'),
	#presentacion
	url(r'^medicamentos/presentacion$', CreatePresentacion.as_view(), name='create_presentacion'),
	)

farmacia/apps/users/urls.py
from django.conf.urls import patterns, url
from .views import Home

urlpatterns = patterns('',
	url(r'^$', 'apps.users.views.userlogin', name="login"),
	url(r'^salir/$', 'apps.users.views.LogOut', name = 'logout'),
#principal
	url(r'^home', Home.as_view(), name='home'),
)

farmacia/farmacia/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'farmacia.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #productos
    url(r'^', include('apps.medicamentos.urls', namespace="medicamentos_app")),

    #agregar ventas.
    url(r'^ventas/', include('apps.ventas.urls', namespace="ventas_app")),

    #login-users
    url(r'^', include('apps.users.urls',  namespace='users_app')),

    #CLientes
    url(r'^', include('apps.clientes.urls',  namespace='clientes_app')),


 #Distribuidores
    url(r'^', include('apps.distribuidor.urls',  namespace='distribuidores_app')),

        #compras
    url(r'^', include('apps.compras.urls',  namespace='compras_app')),
       #compras
    url(r'^', include('apps.laboratorio.urls',  namespace='laboratorios_app')),

     url(r'^todolist/', include('apps.inline.urls',  namespace='todolist')),

       #factura
     url(r'^', include('apps.factura.urls',  namespace='factura_app')),

)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
        )

farmacia/apps/medicamentos/models.py
from django.db import models
from django.db.models import signals
from apps.clientes.models import Cliente
import decimal
import datetime
# Create your models here.
TAX_VALUE = 0.18

# Create your models here.
class Presentacion(models.Model):
	#codigo = models.CharField(max_length=10, unique=True)	
	nombre = models.CharField(max_length=60)

	def __unicode__(self):
		return u'%s' % (self.nombre)

class Medicamentos(models.Model):
	TIPO = (
        ('generico', 'Generico'),
        ('comercial', 'Comercial'),
    )
	lote = models.CharField(max_length=10, unique=True, default=0)
	presentacion = models.ForeignKey(Presentacion)	
	tipo = models.CharField(choices=TIPO, max_length=30)
	nombre = models.CharField(max_length=200, unique=True)
	componente = models.CharField(max_length=200)
	concentracion = models.CharField(max_length=50)
	sanitario = models.CharField(max_length=200)
	fecha_expiracion = models.DateField()
	fecha_produccion = models.DateField()
	descripcion = models.TextField(max_length=400)		
	precio_Compra = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
	precio_venta = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
	stock = models.PositiveSmallIntegerField()
	igv = models.DecimalField(max_digits=6, decimal_places=3, default=0.000)

	def __unicode__(self):
		return self.nombre

	def preeciototal(self):
		precio_total=self.precio_compra*self.stock		
		return precio_total

	def estadomedicamentos(self):
		hoy = datetime.date.today()
		dias = (self.fecha_expiracion - hoy).days
		return dias

	def incrementarlote(self, *args, **kwargs):
		if self.lote == 0:
			self.lote += 1
			self.store.save()
		super(Medicamentos, self).save(*args, **kwargs)



	def save(self, *args, **kwargs):
		if self.precio_venta:
			self.igv = round(float(self.precio_venta) * TAX_VALUE, 3)
			super(Medicamentos, self).save(*args, **kwargs)
		else:
			self.igv=0
			super(Medicamentos, self).save(*args, **kwargs)

farmacia/apps/medicamentos/forms.py
#encoding:utf-8
from django import forms
from .models import Medicamentos, Presentacion


class MedicamentoForm(forms.ModelForm):
	class Meta:
		model = Medicamentos
		exclude = ('lote',)

		widgets = {			
			'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': '6' }),
			'precio_Compra': forms.NumberInput(attrs={'class': 'form-control'}),
			'precio_venta': forms.NumberInput(attrs={'class': 'form-control', 'id':'valor3'}),
			'presentacion': forms.Select(attrs={'class': 'form-control'}),
			'tipo': forms.Select(attrs={'class': 'form-control'}),
			'fecha_expiracion': forms.DateInput(attrs={'class':'form-control', 'id':'Date', 'data-date-format':'dd/mm/yyyy'}),
			'fecha_produccion': forms.DateInput(attrs={'class':'form-control', 'id':'Date1', 'data-date-format':'dd/mm/yyyy'}),
			'igv': forms.NumberInput(attrs={'class': 'form-control', 'id':'total'}),
			}

class CrearmedicamentoForm(forms.ModelForm):
	class Meta:
		model = Medicamentos

		widgets = {
				'lote': forms.TextInput(attrs={'class': 'form-control'}),
				'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': '6' }),
				'precio_Compra': forms.NumberInput(attrs={'class': 'form-control', 'id': 'precio_compra'}),
				'precio_venta': forms.NumberInput(attrs={'class': 'form-control', 'id':'precio_venta'}),
				'presentacion': forms.Select(attrs={'class': 'form-control'}),
				'tipo': forms.Select(attrs={'class': 'form-control'}),
				'fecha_expiracion': forms.DateInput(attrs={'class':'form-control', 'id':'Date', 'data-date-format':'dd/mm/yyyy'}),
				'fecha_produccion': forms.DateInput(attrs={'class':'form-control', 'id':'Date1', 'data-date-format':'dd/mm/yyyy'}),
				'igv': forms.NumberInput(attrs={'class': 'form-control', 'id':'igv'}),
			}


class CrearpresentacionForm(forms.ModelForm):
		class Meta:
			model = Presentacion
			widgets = {
				'nombre': forms.TextInput(attrs={'class': 'form-control'}),
			}

farmacia/apps/medicamentos/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView
from .models import Medicamentos, Presentacion
from .forms import MedicamentoForm, CrearmedicamentoForm, CrearpresentacionForm
from django.http import HttpResponse
import csv


#reporte pdf
from django.http import HttpResponseRedirect
from datetime import *
import xhtml2pdf.pisa as pisa
from django import http
from django.template.loader import get_template
from django.template import Context
import cStringIO as StringIO
import cgi

class ListaMedicamentos(ListView):
	context_object_name = 'medicamentos'
	model = Medicamentos
	template_name = 'medicamentos/lista_medicamentos.html'

class DetalleView(DetailView):
	model = Medicamentos
	template_name = 'medicamentos/detalle_medicamentos.html'

class ActualizarView(UpdateView):
	form_class = CrearmedicamentoForm
	template_name = 'medicamentos/create_update_medicamentos.html'
	model = Medicamentos
	success_url='/medicamentos'

class CreateMedicamentos(CreateView):
	form_class = CrearmedicamentoForm
	template_name = 'medicamentos/create_update_medicamentos.html'
	model = Medicamentos
	success_url = '/medicamentos'

class EliminarView(DeleteView):
	model = Medicamentos
	success_url='/medicamentos'
	template_name = 'medicamentos/eliminar_medicamento.html'


def CargaAtenciones_ant(request):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="atenciones.csv"'
	registrants= Medicamentos.objects.all()
	writer = csv.writer(response,delimiter="|")
	writer.writerow(['id','codigo','categoria','tipo','nombre','componente','concentracion','sanitario','fecha_expiracion','fecha_produccion','descripcion','precio_Compra','precio_venta','stock'])
	for registrant in registrants:
		writer.writerow([registrant.id, 
                            registrant.codigo, 
                            registrant.categoria,
                            registrant.tipo,
                            registrant.nombre.encode('utf-8'),
                            registrant.componente.encode('utf-8'),
                            registrant.concentracion.encode('utf-8'),
                            registrant.sanitario,
                            registrant.fecha_expiracion,
                            registrant.fecha_produccion,
                            registrant.descripcion.encode('utf-8'),
                            registrant.precio_Compra,
                            registrant.precio_venta,
                            registrant.stock
                            ])
	return response


def write_pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return http.HttpResponse(result.getvalue(), \
            content_type='application/pdf')
    return http.HttpResponse('Ocurrio un error al genera el reporte %s' % cgi.escape(html))


def generar_reporte_medicamentos(request):
	 medicamentos = Medicamentos.objects.all()

	 total_precio_compra = 0
	 for expe in medicamentos:
	 	total_precio_compra = (expe.stock*expe.precio_Compra) + total_precio_compra

	 total_precio_venta = 0
	 for expe in medicamentos:
	 	total_precio_venta = (expe.stock*expe.precio_venta) + total_precio_venta

	 ganancia = total_precio_venta - total_precio_compra


	 return write_pdf ('medicamentos/reporte_detalle_medicamentos.html',{'pagesize' : 'legal',
	 				   'medicamentos' : medicamentos, 'total_precio_compra': total_precio_compra,
	 				   'total_precio_venta':total_precio_venta, 'ganancia': ganancia})

#Presentación

class CreatePresentacion(CreateView):
	form_class = CrearpresentacionForm
	template_name = 'medicamentos/create_update_presentacion.html'
	model = Presentacion
	success_url = '/medicamentos/agregar'

farmacia/templates/medicamentos/create_update_medicamentos.html
{% extends "medicamentos/base_medicamentos1.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 


<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Añadir Medicamentos
          </h1>
           <ol class="breadcrumb">
              <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
              <li><a href="{% url 'medicamentos_app:lista_medicamentos' %}">Medicamentos</a></li>
              <li class="active">Nuevo Medicamento</li>
            </ol>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">            
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->

              <div class="box-body">     
                    <div class="row" id ="contenido">
                      <div class="col-lg-12">
                      <form id="form" class="form-horizontal" method="post">
                    {% csrf_token %}
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">  
                                <div class="form-group has-success has-feedback  {% if form.lote.errors %} has-error {% endif %}">
                                     <label class="control-label col-sm-3" for="inputSuccess3">{{ form.lote.label_tag }}
                                     </label>
                                     <div class="col-sm-4">
                                        {{ form.lote }}
                                    </div>
                                 </div>
                                 <div class="form-group has-success has-feedback  {% if form.categoria.errors %} has-error {% endif %}">
                                     <label class="control-label col-sm-3" for="inputSuccess3">{{ form.categoria.label_tag }}
                                     </label>
                                     <div class="col-sm-5">
                                        {{ form.categoria }}
                                    </div>
                                 </div>
                                 <div class="form-group has-success has-feedback  {% if form.presentacion.errors %} has-error {% endif %}">
                                     <label class="control-label col-sm-3" for="inputSuccess3">{{ form.presentacion.label_tag }}
                                     </label>
                                     <div class="col-sm-5">
                                        {{ form.presentacion }}
                                    </div>
                                    <div class="col-sm-4">                                        
                                          <a href="{% url 'medicamentos_app:create_presentacion' %}" class="btn btn-success">+
                                          </a> 
                                    </div>
                                 </div>

                                 <div class="form-group has-success has-feedback  {% if form.tipo.errors %} has-error {% endif %}">
                                     <label class="control-label col-sm-3" for="inputSuccess3">{{ form.tipo.label_tag }}
                                     </label>
                                     <div class="col-sm-6">
                                        {{ form.tipo }}
                                    </div>
                                 </div> 
                                <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                                    <div class="col-sm-6">               
                                     <input type="text" id="disabledTextInput" name="nombre" class="form-control" value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'> 
                                    </div>
                                </div> 
                                <div class="form-group has-success has-feedback  {% if form.componente.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.componente.label_tag }}</label>
                                    <div class="col-sm-6">                                 
                                        <input type="text" id="disabledTextInput" name="componente" class="form-control" value='{% if form.componente.value %}{{ form.componente.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.componente.errors.as_text}}' autofocus='true'>                   
                                    </div>
                                </div> 
                              

                                <div class="form-group has-success has-feedback  {% if form.concentracion.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.concentracion.label_tag }}</label>
                                    <div class="col-sm-6">                 
                                        <input type="text" id="disabledTextInput" name="concentracion" class="form-control" value='{% if form.concentracion.value %}{{ form.concentracion.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.concentracion.errors.as_text}}' autofocus='true'>                    
                                    </div>
                                </div>
                                <div class="form-group has-success has-feedback  {% if form.sanitario.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.sanitario.label_tag }}</label>
                                    <div class="col-sm-6">
                                        <input type="text" id="disabledTextInput" name="sanitario" class="form-control" value='{% if form.sanitario.value %}{{ form.sanitario.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.sanitario.errors.as_text}}' autofocus='true'>
                                    </div>
                                </div> 
                               

                                <div class="form-group has-success has-feedback  {% if form.fecha_expiracion.errors %} has-error {% endif %}">
                                  <label class="col-md-2 control-label" for="Date">{{ form.fecha_expiracion.label_tag }}</label>
                                  <div class="col-md-7">
                                      <div class="input-group">
                                          <div class="input-group-addon">
                                              <i class="fa fa-calendar"></i>
                                          </div>
                                          {{ form.fecha_expiracion }}
                                          </div>
                                  </div>
                                </div>

                                <div class="form-group has-success has-feedback  {% if form.fecha_produccion.errors %} has-error {% endif %}">
                                  <label class="col-md-2 control-label" for="Date">{{ form.fecha_produccion.label_tag }}</label>
                                  <div class="col-md-7">
                                      <div class="input-group">
                                          <div class="input-group-addon">
                                              <i class="fa fa-calendar"></i>
                                          </div>
                                          {{ form.fecha_produccion }}
                                      </div>
                                  </div>
                                </div>

                                </div>                             
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">  
                                 
                                <div class="form-group has-success has-feedback  {% if form.descripcion.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.descripcion.label_tag }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group">
                                         {{ form.descripcion }}
                                        </div>                                       
                                    </div>
                                </div> 
                                <div class="form-group has-success has-feedback  {% if form.stock.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.stock.label_tag }}</label>
                                    <div class="col-sm-6">
                                        <input type="number" id="disabledTextInput" name="stock" class="form-control" value='{% if form.stock.value %}{{ form.stock.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.stock.errors.as_text}}' autofocus='true'> 
                                    </div>
                                </div> 

                                <div class="form-group has-success has-feedback  {% if form.precio_Compra.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.precio_Compra.label_tag }}</label>
                                    <div class="col-sm-6">  
                                        {{ form.precio_Compra}}              
                                    </div>
                                </div>  
                                <div class="form-group has-success has-feedback  {% if form.precio_venta.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.precio_venta.label_tag }}</label>
                                    <div class="col-sm-6">  
                                         {{ form.precio_venta}}              
                                    </div>
                                </div>
                                
                               <div class="form-group has-success has-feedback  {% if form.igv.errors %} has-error {% endif %}">
                                    <label class="control-label col-sm-3" for="inputSuccess3">{{ form.igv.label_tag }}</label>
                                    <div class="col-sm-6">  
                                         {{ form.igv}}              
                                    </div>
                                </div>                               
                        </div>
                        <div class="pull-right">
                            <div class="btn-group">
                            <button type="submit" class="btn btn-lg btn-info"><i class="fa fa-floppy-o"></i></button>
                        </div>
                        </div>  
                    </form>  
                        
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
  
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/medicamentos/create_update_presentacion.html
{% extends "medicamentos/base_medicamentos1.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Clientes
          </h1>
           <ol class="breadcrumb">
              <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
              <li><a href="{% url 'medicamentos_app:create_medicamentos' %}">Nuevo Medicamento</a></li>
           </ol>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
            <a href="{% url 'medicamentos_app:create_medicamentos' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
            </a>             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->

              <div class="box-body">     
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">  
                      <form action="" method="post">{% csrf_token %}
                                <div class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                                     <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}
                                     </label>
                                     <div class="col-sm-6">
                                        {{ form.nombre }}
                                    </div>
                                 </div>                         
                              
                               <div class="pull-right">
                            <div class="btn-group">
                            <button type="submit" class="btn btn-lg btn-info"><i class="fa fa-floppy-o"></i></button>
                        </div>
                        </div>  
                          </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
  
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}

farmacia/templates/medicamentos/lista_medicamentos.html
{% extends "medicamentos/base_medicamentos1.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}    
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Medicamentos
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'users_app:home' %}"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li  class="active">Medicamentos</li>
            <li> <a href="{% url 'medicamentos_app:create_medicamentos'%}">Nuevo Medicamento</a> </li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title">
                      <a href="{% url 'medicamentos_app:create_medicamentos' %}" class="btn btn-success">
                      Nuevo
                      </a>
                      {% for group in user.groups.all %}
                        {% if group.name == 'administrador' %}
                      <a  class="btn btn-primary pull-right" href="/medicamentos/reporte">imprimir</a>
                       {% endif %}
                       {% endfor %}
                      
                    </h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                             <th>N°</th>                                                     
                              <th>Presentacion</th> 
                              <th>Tipo</th>                              
                              <th>Nombre</th> 
                              <th>Precio</th>
                              <th>Vencimiento Dias - Fecha</th> 
                              <th>Stock</th>
                               <th>Acciones</th>                        
                           </tr>
                        </thead>
                      <tbody> 
                      {% for m in medicamentos %}          

                          <tr> 
                              <td>{{ forloop.counter}}</td>                             
                              <td>{{ m.presentacion }} </td> 
                              <td>{{ m.tipo }}</td>                              
                              <td>{{ m.nombre|lower}}</td> 
                              <td>{{m.precio_venta}}</td>
                              {% if m.estadomedicamentos > 30 %}
                                  <td><b style="color:green;">{{m.estadomedicamentos}} - {{m.fecha_expiracion|date:'d/m/Y' }}</b></td>
                              {% elif m.estadomedicamentos <= 30 and m.estadomedicamentos > 0 %}
                                  <td><b style="color:rgb(243, 156, 18);">{{m.estadomedicamentos}} - {{m.fecha_expiracion|date:'d/m/Y' }}</b></td>
                              {% else %}
                              <td><b style="color:red;">{{m.estadomedicamentos}} - {{m.fecha_expiracion|date:'d/m/Y' }}</b></td>
                              {% endif %}   

                              {% if m.stock > 0 and m.stock < 10 %}                             
                              <td><b style="color:red;">{{ m.stock}}</b></td>   
                              {% elif m.stock > 10 and m.stock < 50 %}
                               <td><b style="color:rgb(243, 156, 18);">{{ m.stock}}</b></td>
                               {% else %}
                               <td><b style="color:green;">{{ m.stock}}</b></td>

                              {% endif %}
                              <td class="text-right">
                                  <a href="{% url 'medicamentos_app:detalle_medicamentos' m.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  <a href="{% url 'medicamentos_app:actualizar_medicamentos' m.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% for group in user.groups.all %}
                                    {% if group.name == 'administrador' %}

                                  <a href="{% url 'medicamentos_app:eliminar_medicamentos' m.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a> 
                                  {% endif %}
                                  {% endfor %}
                              </td>
                          </tr>
                      {% endfor %}
                          
                          </tbody>
                      </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}    
 {% endblock producto %}
{% endblock content %}